function main()
    player.JumpToPosition(0, -3)
    sound.PlayBGM("title")
    fadePanel.PlayFadeIn()
    message.Wait(1)    
    message.ShowMessage("勇者「今日も一日頑張った！")
    coroutine.yield()
    player.MoveTo("up", 3)
    coroutine.yield()
    message.ShowMessage("勇者「お腹減ったなぁ\n 何かないかな？")
    coroutine.yield()
    player.MoveTo("right", 2)
    coroutine.yield()
    player.Look("down")
    coroutine.yield()
    message.ShowMessage("（パカ）")
    player.StopAnim()
    coroutine.yield()
    message.ShowMessage("勇者「お！こんなところに美味しそうな塩焼きがあるじゃないか！")
    coroutine.yield()
    select.Choose("食べる", "食べない")
    userInput = coroutine.yield(result)
    while userInput == 1 do
        message.ShowMessage("勇者「なにか別のものをさがすか") -- 一度別の行動ができるといい
        -- ユーザー移動可能
        -- フラグが進む
        -- message.Wait(2)
        coroutine.yield()
        message.ShowMessage("勇者「やっぱりこの塩焼きが食べたいなぁ...")
        coroutine.yield()    
        select.Choose("食べる", "食べない")
        userInput = coroutine.yield(result)    
    end
    message.ShowMessage("勇者「食べちゃお！いただきまぁす")
    coroutine.yield()
    message.ShowMessage("勇者「（むしゃ...むしゃ...）")
    coroutine.yield()
    message.ShowMessage("勇者「これめっちゃおいしいな!\n もう１つあるぞ")
    coroutine.yield()
    select.Choose("食べる", "食べない")
    userInput = coroutine.yield(result)
    while userInput == 1 do
        message.ShowMessage("勇者「さすがに食べ過ぎかな...") -- 一度別の行動ができるといい
        coroutine.yield()
        message.ShowMessage("勇者「でもやっぱり食べたいなぁ...")
        coroutine.yield()    
        select.Choose("食べる", "食べない")
        userInput = coroutine.yield(result)    
    end
    message.ShowMessage("勇者「（むしゃ...むしゃ...）")
    coroutine.yield()
    message.ShowMessage("勇者「うぅぅぅぅぅん\n とってもおいしい")
    coroutine.yield()
    message.ShowMessage("勇者「もう１つあるぞ")
    coroutine.yield()
    select.Choose("食べる", "食べない")
    userInput = coroutine.yield(result)
    while userInput == 1 do
        message.ShowMessage("勇者「さすがに食べ過ぎかな...") -- 一度別の行動ができるといい
        -- ユーザー移動可能
        -- フラグが進む
        message.Wait(2)
        coroutine.yield()
        message.ShowMessage("勇者「でもやっぱり食べたいなぁ...")
        coroutine.yield()
        select.Choose("食べる", "食べない")
        userInput = coroutine.yield(result)    
    end
    message.ShowMessage("勇者「（むしゃ...むしゃ...）")
    coroutine.yield()
    message.ShowMessage("姫様「ちょっとあんた！何食べてんのよ！")
    npcGirl.MoveTo("right", 8)
    coroutine.yield()
    npcGirl.StopAnim()
    message.ShowMessage("王「なんだ？なんだ？")
    npcBoy.Show(true)
    coroutine.yield()
    npcBoy.MoveTo("down", 4)
    coroutine.yield()
    npcBoy.Look("left")
    coroutine.yield()
    npcBoy.StopAnim()
    coroutine.yield()
    message.ShowMessage("姫様「それは明日のお花見のために作ってたやつなんだから！")
    coroutine.yield()
    message.ShowMessage("勇者「ぎょぎょ！！")
    coroutine.yield()
    message.ShowMessage("王様「え！勇者食べちゃった！？")
    coroutine.yield()
    message.ShowMessage("王様「それ伝説のシママスって魚で\n 釣り名人が何日もかけてとったやつだよ")
    coroutine.yield()
    message.ShowMessage("王様「まぁ...")
    coroutine.yield()
    message.ShowMessage("王様「いつも勝手に人のものとってるから\n 今回も悪気はなかったんだろけど...")
    coroutine.yield()
    message.ShowMessage("姫様「そんなこといったって　どうするのよ...\n シママス3匹なんて簡単に手に入らないわよ...")
    coroutine.yield()
    message.ShowMessage("姫様「明日のお花見楽しみにしてたのに...")
    coroutine.yield()
    message.ShowMessage("姫様「えぇん... もう寝る！")
    npcGirl.MoveTo("left", 8)
    coroutine.yield()
    message.ShowMessage("王様「...")
    coroutine.yield()
    message.ShowMessage("勇者「...")
    coroutine.yield()
    message.ShowMessage("王様「やっちゃったね")
    coroutine.yield()
    player.Look("rihgt")
    player.StopAnim()
    message.ShowMessage("勇者「やっちゃいましたね")
    coroutine.yield()
    message.ShowMessage("王様「とりあえず...魔王討伐はいいから\n 魚を手に入れようか")
    coroutine.yield()
    message.ShowMessage("勇者「ありがとうございます...\nでもどうやって")
    coroutine.yield()
    message.ShowMessage("王様「じつわ...")
    coroutine.yield()
    message.ShowMessage("王様「しまづ外来研究所で発明された\n 特別な釣りざおがあってね")
    coroutine.yield()
    message.ShowMessage("王様「まだ実験段階なんだけど\n これを使うとシママスが釣れやすくなるみたいよ")
    coroutine.yield()
    message.ShowMessage("王様「世に出回るとシママスの数も減ってしまう\n から秘密にしてたんだけど...")
    coroutine.yield()
    message.ShowMessage("王様「これで釣ってきたら？")
    coroutine.yield()
    message.ShowMessage("勇者「え！いいんですか？")
    coroutine.yield()
    message.ShowMessage("王様「今回は仕方がない\n 博士によると家の前の川でも釣れるらしいよ")
    coroutine.yield()
    message.ShowMessage("勇者「ありがとうございます！\n さっそく試してきます")
    coroutine.yield()
    message.ShowMessage("王様「おいおい！")
    player.MoveTo("left", 2)
    coroutine.yield()
    message.ShowMessage("王様「勇者！ まだ釣り方を知らんでしょ\n 魚が止まっているときにSPACEだよ！")
    coroutine.yield()
    message.ShowMessage("勇者「ありがとうございます！")
    player.MoveTo("down", 3)
    coroutine.yield()
    player.Show(false)
    camera.JumpTo("down", 10)
    coroutine.yield()
    message.ClearMessage()
    player.Show(true)
    message.Wait(1)
    coroutine.yield()
    player.JumpToPosition(0, -7)
    player.MoveTo("down", 3)
    coroutine.yield()
    player.MoveTo("right", 5)
    message.ShowMessage("勇者「よぉぉし 釣るぞ！！！")
    flag.SetFlag("GetFish", false)
    coroutine.yield()
    fishing()
    coroutine.yield()

    for i=0,1 do
        flag.SetFlag("GetFish", false)
        leftCount = 2-i
        message.ShowMessage("勇者「あと"..leftCount.."匹だ！！")
        coroutine.yield()
        fishing()
    end

    npcBoy.JumpToPosition(3, 4)
    npcBoy.Show(false)
    message.ShowMessage("勇者「やったぁ！！\n これで3匹用意できたぞ！")
    coroutine.yield()
    message.ShowMessage("勇者「さっそく姫様に伝えよう！！")
    coroutine.yield()
    message.ClearMessage()
    player.MoveTo("left", 5)
    coroutine.yield()
    player.MoveTo("up", 3)
    coroutine.yield()
    player.Show(false)
    camera.JumpTo("up",10)
    message.Wait(1)
    message.ShowMessage("勇者「姫様！姫様！")
    player.Show(true)
    player.JumpToPosition(0, -3)
    coroutine.yield()
    player.MoveTo("up", 3)
    coroutine.yield()
    player.Look("down")
    message.ShowMessage("姫様「なによぉ！もぅ寝てたのに！")
    npcGirl.MoveTo("right", 6)
    coroutine.yield()
    npcGirl.StopAnim()
    npcBoy.Look("down")
    coroutine.yield()
    message.ShowMessage("王「おぉ！！")
    npcBoy.Show(true)
    npcBoy.StopAnim()
    coroutine.yield()
    npcBoy.MoveTo("down", 4)
    coroutine.yield()
    npcBoy.MoveTo("left", 2)
    coroutine.yield()
    npcBoy.StopAnim()
    coroutine.yield()
    player.Look("left")
    player.StopAnim()
    message.ShowMessage("勇者「伝説のシママスを3匹釣ってきました！\n ほうとうにすみませんこれでなんとか...")
    coroutine.yield()
    message.ShowMessage("姫様「あら！すごいじゃない！\n 街の釣り名人でも何日もかかったのに！")
    coroutine.yield()
    message.ShowMessage("姫様「いいわ 許してあげる！\n 今後は勝手に食べないでよね ")
    coroutine.yield()
    message.ShowMessage("勇者「はぁい！")
    coroutine.yield()
    message.ShowMessage("姫様「無事シママスも手に入ったことだし\n 早速今から作らないと")
    coroutine.yield()
    npcGirl.Look("left")
    coroutine.yield()
    npcGirl.MoveTo("left", 6)
    message.ShowMessage("姫様「あぁ楽しみ♪楽しみ♪")
    coroutine.yield()
    message.ShowMessage("王様「ほっ...")
    coroutine.yield()
    -- 次の日
    sound.StopBGM()
    fadePanel.PlayFadeOut()
    coroutine.yield()
    message.ClearMessage()
    coroutine.yield()
    message.Wait(1)
    coroutine.yield()
    player.Look("down")
    message.ShowMessage("次の日...")
    coroutine.yield()
    camera.JumpTo("down", 20)
    player.JumpToPosition(0,-20)
    npcBoy.JumpToPosition(1,-20)
    npcGirl.JumpToPosition(-1,-20)
    coroutine.yield()
    npcBoy.Look("down")
    npcGirl.Look("down")
    player.Look("down")
    coroutine.yield()
    message.Wait(1)
    coroutine.yield()
    sound.PlayBGM("title")
    fadePanel.PlayFadeIn()
    coroutine.yield()
    message.ShowMessage("姫様「ほんと桜が綺麗ね")
    coroutine.yield()
    message.ShowMessage("王様「そうだねぇ\n お弁当もおいしかったしありがとね")
    coroutine.yield()
    message.ShowMessage("姫様「あったり前じゃない！ ただ...\n 甘いものも食べたくなってきたわね")
    coroutine.yield()
    message.ShowMessage("勇者「姫様！ちょうどいいものがありますよ！")
    player.Look("left")
    coroutine.yield()
    player.StopAnim()
    npcBoy.StopAnim()
    npcGirl.StopAnim()
    message.ShowMessage("姫様「あら！何かしら？")
    coroutine.yield()
    message.ShowMessage("（お団子を渡す勇者）")
    coroutine.yield()
    message.ShowMessage("姫様「これは全然手に入らなくて有名な\n お団子じゃない！")
    coroutine.yield()
    message.ShowMessage("姫様「私も2ヶ月待って\n やっと手にいれたのにすごいわね\n あなたこれどうやって手に入れたの？")
    coroutine.yield()
    message.ShowMessage("勇者「はい！家の宝箱で手に入れました！")
    coroutine.yield()
    message.ShowMessage("姫様と王様「...")
    coroutine.yield()
    sound.StopBGM()
    message.ClearMessage()
    fadePanel.PlayFadeOut()
    coroutine.yield()
    message.Wait(2)
    coroutine.yield()
    message.ShowMessage("おしまい")
    coroutine.yield()
    message.Wait(2)
    coroutine.yield()
    sound.PlayBGM("title")
    message.ShowMessage("っとまぁ...\n世の中には悪気がなく\nやってしまうことがありますが")
    coroutine.yield()
    message.ShowMessage("もしかすると...\nそのほうが問題だったりするかもしれませんね")
    coroutine.yield()
    message.ShowMessage("スタジオしまづ事件簿\nはらぺこ勇者と川のしま釣り\nお楽しみいただけましたでしょうか")
    coroutine.yield()
    message.ShowMessage("それではまた...どこかの世界で...")
    coroutine.yield()
    message.ShowMessage("あ...そうそう...それではこちらも初めましょう！")
    coroutine.yield()
    message.ShowMessage("第19回スタジオしまづ祭「花よりUnity！？」\n開始です！")
    sound.StopBGM()
    coroutine.yield()
end
function fishing()
    message.ShowMessage("（勇者は釣りざおを投げた...）")
    coroutine.yield()
    message.ShowMessage("（...）")
    coroutine.yield()
    message.ShowMessage("勇者「まだかな...")
    coroutine.yield()
    message.ShowMessage("（...）")
    coroutine.yield() 
    message.ShowMessage("（ピクピク...ピクン！！）")
    coroutine.yield() 
    message.ShowMessage("勇者「お！！かかった！つるぞ！！！！")
    coroutine.yield()
    message.Wait(1)
    message.ClearMessage()
    sceneLoader.LoadScene("MainFishing")
    coroutine.yield()    
    while not flag.GetFlag("GetFish") do
        coroutine.yield()
        message.ClearMessage()
        message.ShowMessage("勇者「うぉぉぉ！！逃がした魚はデカイぜ！")
        coroutine.yield()
        message.ShowMessage("勇者「もう一回だ！")
        coroutine.yield()
        -- さなか釣り
        message.ShowMessage("（勇者は釣りざおを投げた...）")
        coroutine.yield()
        message.ShowMessage("（...）")
        coroutine.yield()
        message.ShowMessage("勇者「まだかな...")
        coroutine.yield()
        message.ShowMessage("（...）")
        coroutine.yield() 
        message.ShowMessage("（ピクピク...ピクン！！）")
        coroutine.yield() 
        message.ShowMessage("勇者「お！！かかった！つるぞ！！！！")
        coroutine.yield()
        message.Wait(1)
        message.ClearMessage()
        sceneLoader.LoadScene("MainFishing")
        coroutine.yield()
    end
    message.ShowMessage("勇者は伝説のシママスを手に入れた")
    coroutine.yield()
end
